import { loadMappings, lookupIntent } from '../registry.js';
import { loadDefaults, MODE_TO_MAP, readString, truthy } from '../utils.js';
import type { DetectedIntent, IdeaVimResult, KeymapMode, Registry } from '../types.js';

function normalizeMode(mode: unknown): KeymapMode | null {
    if (typeof mode !== 'string' || !(mode in MODE_TO_MAP)) {
        return null;
    }
    return mode as KeymapMode;
}

function pickMapCommand(mode: KeymapMode, noremap = false): string {
    const table = MODE_TO_MAP[mode];
    return noremap ? table.noremap : table.map;
}

export function generateIdeaVimrc(
    keymaps: DetectedIntent[] = [],
    options: { registry?: Registry } = {}
): IdeaVimResult {
    const registry = options.registry ?? loadMappings();
    const defaults = loadDefaults();
    const defaultKeymaps = defaults.keymaps;

    const userBindings = new Set<string>();
    for (const keymap of keymaps) {
        const mode = normalizeMode(keymap.mode);
        const lhs = readString(keymap.lhs);
        if (!mode || !lhs) {
            continue;
        }
        userBindings.add(`${mode}|${lhs}`);
    }

    const defaultLines: string[] = [];
    let defaultsAdded = 0;
    for (const def of defaultKeymaps) {
        const mode = normalizeMode(def.mode);
        const lhs = readString(def.lhs);
        if (!mode || !lhs) continue;
        if (userBindings.has(`${mode}|${lhs}`)) {
            continue;
        }

        const action = lookupIntent(def.intent, 'intellij', registry);
        if (!action) continue;

        const mapCmd = pickMapCommand(mode);
        defaultLines.push(`${mapCmd} ${def.lhs} <Action>(${action})`);
        defaultsAdded += 1;
    }

    const mapped: string[] = [];
    const pureVimLines: string[] = [];
    const manual: Array<{ lhs: string; intent: string }> = [];
    const seen = new Set<string>();

    for (const keymap of keymaps) {
        const lhs = readString(keymap.lhs);
        const mode = normalizeMode(keymap.mode);
        if (!lhs || !mode) {
            continue;
        }

        if (!keymap.intent) {
            const rhs = readString(keymap.raw_rhs);
            if (!rhs || rhs === '<Lua function>') {
                continue;
            }

            const mapCmd = pickMapCommand(mode, keymap.opts.noremap);
            const flags: string[] = [];
            if (truthy(keymap.opts.silent)) flags.push('<silent>');
            if (truthy(keymap.opts.expr)) flags.push('<expr>');
            if (truthy(keymap.opts.nowait)) flags.push('<nowait>');
            if (truthy(keymap.opts.buffer)) flags.push('<buffer>');

            const line = `${[mapCmd, ...flags].join(' ')} ${lhs} ${rhs}`;
            const key = `${mode}|${lhs}|${mapCmd}|${flags.join(',')}`;
            if (!seen.has(key)) {
                seen.add(key);
                pureVimLines.push(line);
            }
            continue;
        }

        const action = lookupIntent(keymap.intent, 'intellij', registry);
        if (!action) {
            manual.push({ lhs, intent: keymap.intent });
            continue;
        }

        const mapCmd = pickMapCommand(mode, true);
        const flags: string[] = [];
        if (truthy(keymap.opts.silent)) flags.push('<silent>');
        if (truthy(keymap.opts.expr)) flags.push('<expr>');
        if (truthy(keymap.opts.nowait)) flags.push('<nowait>');
        if (truthy(keymap.opts.buffer)) flags.push('<buffer>');

        const line = `${[mapCmd, ...flags].join(' ')} ${lhs} <Action>(${action})`;
        const key = `${mode}|${lhs}|${action}|${mapCmd}|${flags.join(',')}`;
        if (seen.has(key)) {
            continue;
        }
        seen.add(key);
        mapped.push(line);
    }

    const lines = ['" Generated by nvim-keymap-migrator', '" IntelliJ IdeaVim action mappings', ''];

    if (defaultLines.length > 0) {
        lines.push('" Default LSP keymaps (from Neovim defaults)');
        lines.push(...defaultLines);
        lines.push('');
    }

    if (pureVimLines.length > 0) {
        lines.push('" Pure Vim mappings (native Vim motions)');
        lines.push(...pureVimLines);
        lines.push('');
    }

    if (mapped.length === 0 && pureVimLines.length === 0) {
        lines.push('" No IDE-translatable mappings detected.');
    } else {
        lines.push(...mapped);
    }

    lines.push('');
    lines.push(`" Generated actions: ${defaultLines.length + mapped.length}`);
    lines.push(`" Pure Vim mappings: ${pureVimLines.length}`);
    lines.push(`" Manual mappings: ${manual.length}`);

    if (manual.length > 0) {
        lines.push('" Manual review:');
        for (const item of manual.slice(0, 20)) {
            lines.push(`" ${item.lhs} -> ${item.intent}`);
        }
    }

    return { text: `${lines.join('\n')}\n`, defaultsAdded };
}
