import type { DetectedIntent, KeymapMode } from '../types.js';
import { MODE_TO_MAP, truthy } from '../utils.js';

function pickMapCommand(mode: KeymapMode, noremap: boolean): string {
    const table = MODE_TO_MAP[mode] ?? { noremap: 'noremap', map: 'map' };
    return truthy(noremap) ? table.noremap : table.map;
}

function normalizeMode(mode: unknown): KeymapMode | null {
    if (typeof mode !== 'string' || mode.length === 0 || !(mode in MODE_TO_MAP)) {
        return null;
    }
    return mode as KeymapMode;
}

function toVimMapLine(keymap: DetectedIntent): string | null {
    const mode = normalizeMode(keymap.mode);
    if (!mode) return null;

    const lhs = keymap.lhs.trim();
    const rhs = keymap.raw_rhs.trim();
    if (!lhs || !rhs || rhs === '<Lua function>') {
        return null;
    }

    if (lhs.startsWith('<Plug>') || lhs.startsWith('<plug>')) {
        return null;
    }

    if (keymap.intent && keymap.translatable) {
        return null;
    }

    const flags: string[] = [];
    if (truthy(keymap.opts.silent)) flags.push('<silent>');
    if (truthy(keymap.opts.expr)) flags.push('<expr>');
    if (truthy(keymap.opts.nowait)) flags.push('<nowait>');
    if (truthy(keymap.opts.buffer)) flags.push('<buffer>');

    const prefix = [pickMapCommand(mode, keymap.opts.noremap), ...flags].join(' ');
    return `${prefix} ${lhs} ${rhs}`;
}

export function generateVimrc(keymaps: DetectedIntent[] = []): string {
    const lines = ['" Generated by nvim-keymap-migrator', '" Shared pure-Vim mappings', ''];

    let generated = 0;
    let skipped = 0;

    for (const keymap of keymaps) {
        const line = toVimMapLine(keymap);
        if (!line) {
            skipped += 1;
            continue;
        }
        lines.push(line);
        generated += 1;
    }

    if (generated === 0) {
        lines.push('" No pure Vim-compatible mappings detected.');
    }

    lines.push('');
    lines.push(`" Generated mappings: ${generated}`);
    lines.push(`" Skipped mappings: ${skipped}`);

    return `${lines.join('\n')}\n`;
}

export function isPureVimMapping(keymap: DetectedIntent): boolean {
    return Boolean(toVimMapLine(keymap));
}
